spring:
  config:
    activate:
      on-profile: "qa"
myreads:
  url: "https://nithyaluv2code.github.io/reads/myreads.html?year=2025"
  description: "These books are hard copies, ebooks and audibles.(QA Version)"
  sorting: "The books are sorted based on their most recent read date."
  whatdoimean: "If I have read or listened to a book in 2003, 2006 and 2016, you will see them only under 2024"
  whomtocontact: "{cipher}c49a1d9e8d0bdc66d126a7a5082c135ad5c9d6b5a78907b3f7c1e82eafc67d903ab60766e20010b9b00c5fec7440caa6"
